Update to Node.js LTS version 20.9.0 [LW-8997]
DominikGuzei/nami pull request #1
Opened 2023-11-06 11:16 UTC by DominikGuzei

This PR updates the project to the Node.js LTS version 20.9.0.

**Please note:** the small change regarding `react` and `react-dom` version was necessary to fix peer dependency issues. The upgrade to newer npm dependencies will be resolved in a different PR.

2023-11-06 11:18 UTC, rhyslbw approved these changes

2023-11-06 11:18 UTC, DominikGuzei commented on package.json
> +    "sass": "1.69.5",
This was necessary to fix some `npm install` issues due to building native libraries (`node-sass` is deprecated)

2023-11-06 11:19 UTC, DominikGuzei commented on package.json
> +    "react": "17.0.1",
the small change regarding react and react-dom version was necessary to fix peer dependency issues. The upgrade to newer npm dependencies will be resolved in a different PR.

2023-11-06 11:19 UTC, rhyslbw requested changes
Dependencies are not resolving in the CI run

2023-11-06 14:27 UTC, DominikGuzei commented
@rhyslbw all issues fixed now with minimal changes 💪

2023-11-06 14:28 UTC, DominikGuzei commented on .npmrc
> +legacy-peer-deps=true
This is necessary because otherwise `npm install` would fail with node 20 (we need to upgrade the dependencies in another PR)

2023-11-06 14:29 UTC, DominikGuzei commented on package.json
> +    "@ledgerhq/hw-transport-webusb": "6.11.2",
It was necessary to pin this dependency to the old version because the newest version broke the test suite

2023-11-06 14:30 UTC, DominikGuzei commented on package.json
> +    "nan": "2.17.0"
It was necessary to pin the "nan" package to this newer version because otherwise it broke the `npm install` of binaries on the newer node version.

2023-11-06 14:36 UTC, mkazlauskas approved these changes
LGTM

2023-11-06 14:38 UTC, lucas-barros approved these changes

2023-11-10 11:04 UTC, rhyslbw approved these changes

2023-11-23 12:18 UTC, DominikGuzei commented
Since Github doesn't allow changing the base repository for a PR, I'm closing this in favor of https://github.com/input-output-hk/nami/pull/884

2023-11-23 12:18 UTC, closed without merging